name: pr-loop

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
jobs:
  pr-loop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: run e2e pipeline test
        run: |
          . ./.github/workflows/pr-loop.ps1
          Invoke-EndToEndPipelineTest -Org ${{ secrets.AZDO_PROJECT }} -Pat ${{ secrets.AZDO_PAT }}
        shell: pwsh